inherit_gem:
  onkcop:
    - "config/rubocop.yml"
    # uncomment if use rails cops
    - "config/rails.yml"
    # uncomment if use rspec cops
    - "config/rspec.yml"

AllCops:
  TargetRubyVersion: 2.4
  # uncomment if use rails cops
  # TargetRailsVersion: 5.1

RSpec/DescribeClass:
  Exclude:
    - spec/requests/**/*

Metrics/BlockLength:
  Exclude:
    - "Rakefile"
    - "**/*.rake"
    - "spec/**/*.rb"
    - "Gemfile"
    - "Guardfile"
    - "config/environments/*.rb"
    - "config/routes.rb"
    - "config/routes/**/*.rb"
    - "*.gemspec"
    - "config/deploy.rb" # add

Style/GlobalVars:
  Exclude:
    - "config/unicorn/*.rb"

Lint/HandleExceptions:
  Exclude:
    - "config/unicorn/*.rb"
